name: R2S-OpenWrt

on:
  push:
    branches: 
      - master
    paths:
      - '.github/workflows/R2S-OpenWrt.yml'
      - 'SEED/config.seed'
      - 'SCRIPTS/02_prepare_package.sh'
  watch:
    types: [started]

jobs:
  build:
    runs-on: ubuntu-18.04
    if: github.event.repository.owner.id == github.event.sender.id
    
    steps:
    - name: Clone Repository
      uses: actions/checkout@v1
    - name: free disk space
      run: |
        sudo swapoff -a
        sudo rm -f /swapfile
        sudo apt clean
        docker rmi $(docker image ls -aq)
        df -h
        /bin/bash ./SCRIPTS/free_disk_space.sh
    - name: Init build dependencies
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
          sudo rm -rf /etc/apt/sources.list.d
          sudo apt-get -y purge dotnet* ghc* google* llvm* mysql* php* zulu* firefox hhvm
          sudo rm -rf /usr/share/dotnet /usr/local/lib/android/sdk
          sudo apt-get update
          sudo apt-get -y --no-install-recommends install build-essential asciidoc binutils bison bzip2 gawk gettext git libncurses5-dev libz-dev patch python3 unzip zlib1g-dev lib32gcc1 libc6-dev-i386 subversion flex uglifyjs gcc-multilib g++-multilib p7zip p7zip-full msmtp libssl-dev texinfo libglib2.0-dev xmlto qemu-utils upx libelf-dev autoconf automake libtool autopoint device-tree-compiler antlr3 gperf python3
          curl https://raw.githubusercontent.com/friendlyarm/build-env-on-ubuntu-bionic/master/install.sh  | sed '/#/d' | sed 's/\\//g' | sed 's/exit 0//g' | sed 's/sudo apt -y install//g' | sed 's/sudo apt-get -y install//g' | sed 's/:i386//g' | xargs sudo apt-get -y --no-install-recommends install
          sudo rm -rf /usr/share/dotnet /usr/local/lib/android/sdk
          git config --global user.name "Actions"
          git config --global user.email "actions@github.com"
    - name: Cleanup Old Action Artifacts
      uses: kolpav/purge-artifacts-action@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        expire-in: 0days # Setting this to 0 will delete all artifacts
    - name: Prepare Mixedwrt
      run: |
        sudo chown -R runner:runner /home/runner/work/R2S-OpenWrt
        cp -r ./SCRIPTS/. ./
        /bin/bash 01_get_ready.sh
    - name: Prepare Package
      run: |
        cd openwrt
        cp -r ../SCRIPTS/. ./
        /bin/bash 02_prepare_package.sh
    - name: Convert Translation
      run: |
        cd openwrt
        /bin/bash 03_convert_translation.sh
    - name: Remove Upx
      run: |
        cd openwrt
        /bin/bash 04_remove_upx.sh
    - name: Make Config
      run: |
        cd openwrt
        mv ../SEED/config.seed .config
        make defconfig
        chmod -R 755 ./
    - name: Make Toolchain
      run: |
        df -h
        cd openwrt
        let make_process=$(nproc)+1
        make toolchain/install -j${make_process} V=s
    - name: Compile Openwrt
      run: |
        df -h
        cd openwrt
        let make_process=$(nproc)+1
        make -j${make_process} V=s || make -j${make_process} V=s
    - name: Cleaning
      run: |
        df -h
        cd openwrt/bin/targets/rockchip/armv8
        /bin/bash ../../../../../SCRIPTS/05_cleaning.sh
    - name: Print Disk Space After
      run: df -h
    - name: Upload Firmwares
      uses: actions/upload-artifact@master
      with:
        name: R2S-OpenWrt
        path: openwrt/bin/targets/rockchip/armv8/
